import { createContext } from "svelte";

import type { HighlighterCore } from "shiki";
import type { RootProps } from "./code-root.svelte";

import { getHighlighter } from "./shiki";

type CodeContextOptions = {
	readonly code: string;
	readonly lang: NonNullable<RootProps["lang"]>;
	readonly loadLanguage: RootProps["loadLanguage"];
	readonly hideLines: boolean;
	readonly highlight: RootProps["highlight"];
};

/** Highlights source code and exposes it to nested code parts. */
export class CodeContext {
	#highlighted = $state("");
	#error = $state<unknown>();

	/** @param options - Reactive source, language loader, line-number, and highlight options. */
	constructor(readonly options: CodeContextOptions) {
		$effect(() => {
			const code = options.code;
			const lang = options.lang;
			const loadLanguage = options.loadLanguage;
			const hideLines = options.hideLines;
			const highlight = options.highlight;
			let cancelled = false;

			this.#highlighted = "";
			this.#error = undefined;

			void getHighlighter(lang, loadLanguage)
				.then((highlighter) => {
					if (!cancelled) this.#highlighted = this.highlight(highlighter, code, lang, hideLines, highlight);
				})
				.catch((error: unknown) => {
					if (!cancelled) this.#error = error;
				});

			return () => (cancelled = true);
		});
	}

	/**
	 * Converts source code into themed Shiki markup and annotates selected lines.
	 *
	 * @param highlighter - Shared Shiki instance with the requested grammar loaded.
	 * @param code - Raw source code to highlight.
	 * @param lang - Loaded Shiki language name or alias.
	 * @param hideLines - Whether line numbers should be omitted.
	 * @param highlight - Individual lines and inclusive ranges to emphasize.
	 * @returns Highlighted HTML generated by Shiki.
	 */
	highlight(highlighter: HighlighterCore, code: string, lang: string, hideLines: boolean, highlight: RootProps["highlight"]) {
		return highlighter.codeToHtml(code, {
			lang,
			themes: {
				light: "github-light-default",
				dark: "github-dark-default"
			},
			transformers: [
				{
					pre: (el) => {
						el.properties.style = "";

						el.properties.tabindex = "-1";

						if (!hideLines) {
							el.properties.class += " line-numbers";
						}

						return el;
					},
					line: (node, line) => {
						if (within(line, highlight)) {
							node.properties.class = node.properties.class + " line--highlighted";
						}

						return node;
					}
				}
			]
		});
	}

	/** Current raw source code. */
	get code() {
		return this.options.code;
	}

	/** Current highlighted markup, or an error from loading or highlighting the requested language. */
	get highlighted() {
		if (this.#error) throw this.#error;
		return this.#highlighted;
	}
}

/**
 * Determines whether a line belongs to any configured line or inclusive range.
 *
 * @param num - One-based line number.
 * @param range - Individual lines and ranges selected for highlighting.
 */
function within(num: number, range: RootProps["highlight"]) {
	if (!range) return false;

	let within = false;

	for (const r of range) {
		if (typeof r === "number") {
			if (num === r) {
				within = true;
				break;
			}
			continue;
		}

		if (r[0] <= num && num <= r[1]) {
			within = true;
			break;
		}
	}

	return within;
}

const [getCodeContext, provideCodeContext] = createContext<CodeContext>();

/** @param options - Reactive source and highlighting options to provide to nested code parts. */
export function setCodeContext(options: CodeContextOptions) {
	return provideCodeContext(new CodeContext(options));
}

/** @returns The state from the nearest code root. */
export { getCodeContext };
